-- Part 1: Support Section (10 keys × 9 languages = 90 translations)
INSERT INTO translations (lang_code, translation_key, translation_value, is_ai_translated) VALUES
('ru', 'settings.support.title', 'Поддержка', false), ('en', 'settings.support.title', 'Support', false), ('kk', 'settings.support.title', 'Қолдау', false), ('es', 'settings.support.title', 'Soporte', false), ('de', 'settings.support.title', 'Unterstützung', false), ('fr', 'settings.support.title', 'Support', false), ('zh', 'settings.support.title', '支持', false), ('ja', 'settings.support.title', 'サポート', false), ('ka', 'settings.support.title', 'მხარდაჭერა', false),
('ru', 'settings.support.contact', 'Связаться с поддержкой', false), ('en', 'settings.support.contact', 'Contact support', false), ('kk', 'settings.support.contact', 'Қолдау қызметіне хабарласу', false), ('es', 'settings.support.contact', 'Contactar soporte', false), ('de', 'settings.support.contact', 'Support kontaktieren', false), ('fr', 'settings.support.contact', 'Contacter le support', false), ('zh', 'settings.support.contact', '联系支持', false), ('ja', 'settings.support.contact', 'サポートに連絡', false), ('ka', 'settings.support.contact', 'მხარდაჭერის დაკავშირება', false),
('ru', 'settings.support.write_us', 'Напишите нам', false), ('en', 'settings.support.write_us', 'Write to us', false), ('kk', 'settings.support.write_us', 'Бізге жазыңыз', false), ('es', 'settings.support.write_us', 'Escríbenos', false), ('de', 'settings.support.write_us', 'Schreiben Sie uns', false), ('fr', 'settings.support.write_us', 'Écrivez-nous', false), ('zh', 'settings.support.write_us', '写信给我们', false), ('ja', 'settings.support.write_us', 'お問い合わせ', false), ('ka', 'settings.support.write_us', 'დაგვწერეთ ჩვენ', false),
('ru', 'settings.support.rate_app', 'Оценить приложение', false), ('en', 'settings.support.rate_app', 'Rate app', false), ('kk', 'settings.support.rate_app', 'Қолданбаны бағалау', false), ('es', 'settings.support.rate_app', 'Calificar app', false), ('de', 'settings.support.rate_app', 'App bewerten', false), ('fr', 'settings.support.rate_app', 'Évaluer app', false), ('zh', 'settings.support.rate_app', '评价应用', false), ('ja', 'settings.support.rate_app', 'アプリを評価', false), ('ka', 'settings.support.rate_app', 'აპლიკაციის შეფასება', false),
('ru', 'settings.support.share_feedback', 'Поделитесь отзывом', false), ('en', 'settings.support.share_feedback', 'Share feedback', false), ('kk', 'settings.support.share_feedback', 'Пікір қалдырыңыз', false), ('es', 'settings.support.share_feedback', 'Compartir opinión', false), ('de', 'settings.support.share_feedback', 'Feedback teilen', false), ('fr', 'settings.support.share_feedback', 'Partager avis', false), ('zh', 'settings.support.share_feedback', '分享反馈', false), ('ja', 'settings.support.share_feedback', 'フィードバックを共有', false), ('ka', 'settings.support.share_feedback', 'გაზიარება გამოხმაურება', false),
('ru', 'settings.support.report_bug', 'Сообщить об ошибке', false), ('en', 'settings.support.report_bug', 'Report bug', false), ('kk', 'settings.support.report_bug', 'Қате туралы хабарлау', false), ('es', 'settings.support.report_bug', 'Reportar error', false), ('de', 'settings.support.report_bug', 'Fehler melden', false), ('fr', 'settings.support.report_bug', 'Signaler bug', false), ('zh', 'settings.support.report_bug', '报告错误', false), ('ja', 'settings.support.report_bug', 'バグを報告', false), ('ka', 'settings.support.report_bug', 'შეცდომის მოხსენება', false),
('ru', 'settings.support.help_improve', 'Помогите улучшить приложение', false), ('en', 'settings.support.help_improve', 'Help improve app', false), ('kk', 'settings.support.help_improve', 'Қолданбаны жақсартуға көмектесіңіз', false), ('es', 'settings.support.help_improve', 'Ayuda a mejorar app', false), ('de', 'settings.support.help_improve', 'App verbessern helfen', false), ('fr', 'settings.support.help_improve', 'Aider à améliorer app', false), ('zh', 'settings.support.help_improve', '帮助改进应用', false), ('ja', 'settings.support.help_improve', 'アプリ改善を手伝う', false), ('ka', 'settings.support.help_improve', 'დაეხმარეთ აპლიკაციის გაუმჯობესებას', false),
('ru', 'settings.support.faq', 'FAQ', false), ('en', 'settings.support.faq', 'FAQ', false), ('kk', 'settings.support.faq', 'Жиі қойылатын сұрақтар', false), ('es', 'settings.support.faq', 'Preguntas frecuentes', false), ('de', 'settings.support.faq', 'Häufige Fragen', false), ('fr', 'settings.support.faq', 'Questions fréquentes', false), ('zh', 'settings.support.faq', '常见问题', false), ('ja', 'settings.support.faq', 'よくある質問', false), ('ka', 'settings.support.faq', 'ხშირად დასმული კითხვები', false),
('ru', 'settings.support.faq_description', 'Часто задаваемые вопросы', false), ('en', 'settings.support.faq_description', 'Frequently asked questions', false), ('kk', 'settings.support.faq_description', 'Жиі қойылатын сұрақтар', false), ('es', 'settings.support.faq_description', 'Preguntas frecuentes', false), ('de', 'settings.support.faq_description', 'Häufig gestellte Fragen', false), ('fr', 'settings.support.faq_description', 'Questions fréquemment posées', false), ('zh', 'settings.support.faq_description', '常见问题解答', false), ('ja', 'settings.support.faq_description', 'よくある質問', false), ('ka', 'settings.support.faq_description', 'ხშირად დასმული კითხვები', false),
('ru', 'settings.support.install_app', 'Установить приложение', false), ('en', 'settings.support.install_app', 'Install app', false), ('kk', 'settings.support.install_app', 'Қолданбаны орнату', false), ('es', 'settings.support.install_app', 'Instalar app', false), ('de', 'settings.support.install_app', 'App installieren', false), ('fr', 'settings.support.install_app', 'Installer app', false), ('zh', 'settings.support.install_app', '安装应用', false), ('ja', 'settings.support.install_app', 'アプリをインストール', false), ('ka', 'settings.support.install_app', 'აპლიკაციის დაყენება', false),
('ru', 'settings.support.pwa_to_home', 'PWA на главный экран', false), ('en', 'settings.support.pwa_to_home', 'PWA to home screen', false), ('kk', 'settings.support.pwa_to_home', 'PWA басты экранға', false), ('es', 'settings.support.pwa_to_home', 'PWA a pantalla principal', false), ('de', 'settings.support.pwa_to_home', 'PWA zum Startbildschirm', false), ('fr', 'settings.support.pwa_to_home', 'PWA sur écran accueil', false), ('zh', 'settings.support.pwa_to_home', 'PWA到主屏幕', false), ('ja', 'settings.support.pwa_to_home', 'PWAをホーム画面に', false), ('ka', 'settings.support.pwa_to_home', 'PWA მთავარ ეკრანზე', false)
ON CONFLICT (lang_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value, updated_at = NOW();

