-- Add all remaining translations for UNITY-v2 i18n system
-- Total: ~450 translations (50 keys × 9 languages)
-- Execute via Supabase SQL Editor or MCP

-- Support Section (10 keys × 9 languages = 90 translations)
INSERT INTO translations (lang_code, translation_key, translation_value, is_ai_translated) VALUES
('ru', 'settings.support.title', 'Поддержка', false), ('en', 'settings.support.title', 'Support', false), ('kk', 'settings.support.title', 'Қолдау', false), ('es', 'settings.support.title', 'Soporte', false), ('de', 'settings.support.title', 'Unterstützung', false), ('fr', 'settings.support.title', 'Support', false), ('zh', 'settings.support.title', '支持', false), ('ja', 'settings.support.title', 'サポート', false), ('ka', 'settings.support.title', 'მხარდაჭერა', false),
('ru', 'settings.support.contact', 'Связаться с поддержкой', false), ('en', 'settings.support.contact', 'Contact support', false), ('kk', 'settings.support.contact', 'Қолдау қызметіне хабарласу', false), ('es', 'settings.support.contact', 'Contactar soporte', false), ('de', 'settings.support.contact', 'Support kontaktieren', false), ('fr', 'settings.support.contact', 'Contacter le support', false), ('zh', 'settings.support.contact', '联系支持', false), ('ja', 'settings.support.contact', 'サポートに連絡', false), ('ka', 'settings.support.contact', 'მხარდაჭერის დაკავშირება', false),
('ru', 'settings.support.write_us', 'Напишите нам', false), ('en', 'settings.support.write_us', 'Write to us', false), ('kk', 'settings.support.write_us', 'Бізге жазыңыз', false), ('es', 'settings.support.write_us', 'Escríbenos', false), ('de', 'settings.support.write_us', 'Schreiben Sie uns', false), ('fr', 'settings.support.write_us', 'Écrivez-nous', false), ('zh', 'settings.support.write_us', '写信给我们', false), ('ja', 'settings.support.write_us', 'お問い合わせ', false), ('ka', 'settings.support.write_us', 'დაგვწერეთ ჩვენ', false),
('ru', 'settings.support.rate_app', 'Оценить приложение', false), ('en', 'settings.support.rate_app', 'Rate app', false), ('kk', 'settings.support.rate_app', 'Қолданбаны бағалау', false), ('es', 'settings.support.rate_app', 'Calificar app', false), ('de', 'settings.support.rate_app', 'App bewerten', false), ('fr', 'settings.support.rate_app', 'Évaluer app', false), ('zh', 'settings.support.rate_app', '评价应用', false), ('ja', 'settings.support.rate_app', 'アプリを評価', false), ('ka', 'settings.support.rate_app', 'აპლიკაციის შეფასება', false),
('ru', 'settings.support.share_feedback', 'Поделитесь отзывом', false), ('en', 'settings.support.share_feedback', 'Share feedback', false), ('kk', 'settings.support.share_feedback', 'Пікір қалдырыңыз', false), ('es', 'settings.support.share_feedback', 'Compartir opinión', false), ('de', 'settings.support.share_feedback', 'Feedback teilen', false), ('fr', 'settings.support.share_feedback', 'Partager avis', false), ('zh', 'settings.support.share_feedback', '分享反馈', false), ('ja', 'settings.support.share_feedback', 'フィードバックを共有', false), ('ka', 'settings.support.share_feedback', 'გაზიარება გამოხმაურება', false),
('ru', 'settings.support.report_bug', 'Сообщить об ошибке', false), ('en', 'settings.support.report_bug', 'Report bug', false), ('kk', 'settings.support.report_bug', 'Қате туралы хабарлау', false), ('es', 'settings.support.report_bug', 'Reportar error', false), ('de', 'settings.support.report_bug', 'Fehler melden', false), ('fr', 'settings.support.report_bug', 'Signaler bug', false), ('zh', 'settings.support.report_bug', '报告错误', false), ('ja', 'settings.support.report_bug', 'バグを報告', false), ('ka', 'settings.support.report_bug', 'შეცდომის მოხსენება', false),
('ru', 'settings.support.help_improve', 'Помогите улучшить приложение', false), ('en', 'settings.support.help_improve', 'Help improve app', false), ('kk', 'settings.support.help_improve', 'Қолданбаны жақсартуға көмектесіңіз', false), ('es', 'settings.support.help_improve', 'Ayuda a mejorar app', false), ('de', 'settings.support.help_improve', 'App verbessern helfen', false), ('fr', 'settings.support.help_improve', 'Aider à améliorer app', false), ('zh', 'settings.support.help_improve', '帮助改进应用', false), ('ja', 'settings.support.help_improve', 'アプリ改善を手伝う', false), ('ka', 'settings.support.help_improve', 'დაეხმარეთ აპლიკაციის გაუმჯობესებას', false),
('ru', 'settings.support.faq', 'FAQ', false), ('en', 'settings.support.faq', 'FAQ', false), ('kk', 'settings.support.faq', 'Жиі қойылатын сұрақтар', false), ('es', 'settings.support.faq', 'Preguntas frecuentes', false), ('de', 'settings.support.faq', 'Häufige Fragen', false), ('fr', 'settings.support.faq', 'Questions fréquentes', false), ('zh', 'settings.support.faq', '常见问题', false), ('ja', 'settings.support.faq', 'よくある質問', false), ('ka', 'settings.support.faq', 'ხშირად დასმული კითხვები', false),
('ru', 'settings.support.faq_description', 'Часто задаваемые вопросы', false), ('en', 'settings.support.faq_description', 'Frequently asked questions', false), ('kk', 'settings.support.faq_description', 'Жиі қойылатын сұрақтар', false), ('es', 'settings.support.faq_description', 'Preguntas frecuentes', false), ('de', 'settings.support.faq_description', 'Häufig gestellte Fragen', false), ('fr', 'settings.support.faq_description', 'Questions fréquemment posées', false), ('zh', 'settings.support.faq_description', '常见问题解答', false), ('ja', 'settings.support.faq_description', 'よくある質問', false), ('ka', 'settings.support.faq_description', 'ხშირად დასმული კითხვები', false),
('ru', 'settings.support.install_app', 'Установить приложение', false), ('en', 'settings.support.install_app', 'Install app', false), ('kk', 'settings.support.install_app', 'Қолданбаны орнату', false), ('es', 'settings.support.install_app', 'Instalar app', false), ('de', 'settings.support.install_app', 'App installieren', false), ('fr', 'settings.support.install_app', 'Installer app', false), ('zh', 'settings.support.install_app', '安装应用', false), ('ja', 'settings.support.install_app', 'アプリをインストール', false), ('ka', 'settings.support.install_app', 'აპლიკაციის დაყენება', false),
('ru', 'settings.support.pwa_to_home', 'PWA на главный экран', false), ('en', 'settings.support.pwa_to_home', 'PWA to home screen', false), ('kk', 'settings.support.pwa_to_home', 'PWA басты экранға', false), ('es', 'settings.support.pwa_to_home', 'PWA a pantalla principal', false), ('de', 'settings.support.pwa_to_home', 'PWA zum Startbildschirm', false), ('fr', 'settings.support.pwa_to_home', 'PWA sur écran accueil', false), ('zh', 'settings.support.pwa_to_home', 'PWA到主屏幕', false), ('ja', 'settings.support.pwa_to_home', 'PWAをホーム画面に', false), ('ka', 'settings.support.pwa_to_home', 'PWA მთავარ ეკრანზე', false),

-- Main Screen - Motivation Cards (6 keys × 9 languages = 54 translations)
('ru', 'home.motivation.card1_title', 'Сегодня отличное время', false), ('en', 'home.motivation.card1_title', 'Today is a great time', false), ('kk', 'home.motivation.card1_title', 'Бүгін тамаша уақыт', false), ('es', 'home.motivation.card1_title', 'Hoy es un gran momento', false), ('de', 'home.motivation.card1_title', 'Heute ist eine großartige Zeit', false), ('fr', 'home.motivation.card1_title', 'Aujourd\'hui est un moment idéal', false), ('zh', 'home.motivation.card1_title', '今天是美好的时光', false), ('ja', 'home.motivation.card1_title', '今日は素晴らしい時間', false), ('ka', 'home.motivation.card1_title', 'დღეს შესანიშნავი დროა', false),
('ru', 'home.motivation.card1_description', 'Запиши маленькую победу — это первый шаг к осознанию своих достижений.', false), ('en', 'home.motivation.card1_description', 'Write down a small victory — it\'s the first step to realizing your achievements.', false), ('kk', 'home.motivation.card1_description', 'Кішкентай жеңісті жазыңыз — бұл жетістіктеріңізді түсінудің бірінші қадамы.', false), ('es', 'home.motivation.card1_description', 'Escribe una pequeña victoria: es el primer paso para reconocer tus logros.', false), ('de', 'home.motivation.card1_description', 'Schreibe einen kleinen Sieg auf — das ist der erste Schritt, um deine Erfolge zu erkennen.', false), ('fr', 'home.motivation.card1_description', 'Notez une petite victoire — c\'est le premier pas vers la prise de conscience de vos réalisations.', false), ('zh', 'home.motivation.card1_description', '记下一个小胜利——这是认识到你的成就的第一步。', false), ('ja', 'home.motivation.card1_description', '小さな勝利を書き留めましょう — それはあなたの成果を認識する最初のステップです。', false), ('ka', 'home.motivation.card1_description', 'ჩაწერეთ პატარა გამარჯვება — ეს არის პირველი ნაბიჯი თქვენი მიღწევების გააზრებისკენ.', false),
('ru', 'home.motivation.card2_title', 'Даже одна мысль делает день осмысленным', false), ('en', 'home.motivation.card2_title', 'Even one thought makes the day meaningful', false), ('kk', 'home.motivation.card2_title', 'Тіпті бір ой күнді мағыналы етеді', false), ('es', 'home.motivation.card2_title', 'Incluso un pensamiento hace que el día sea significativo', false), ('de', 'home.motivation.card2_title', 'Selbst ein Gedanke macht den Tag bedeutungsvoll', false), ('fr', 'home.motivation.card2_title', 'Même une pensée rend la journée significative', false), ('zh', 'home.motivation.card2_title', '即使一个想法也能让这一天变得有意义', false), ('ja', 'home.motivation.card2_title', '一つの考えでさえ、その日を意味のあるものにします', false), ('ka', 'home.motivation.card2_title', 'ერთი აზრიც კი დღეს მნიშვნელოვანს ხდის', false),
('ru', 'home.motivation.card2_description', 'Не обязательно писать много — одна фраза может изменить твой взгляд на прожитый день.', false), ('en', 'home.motivation.card2_description', 'You don\'t have to write a lot — one phrase can change your view of the day.', false), ('kk', 'home.motivation.card2_description', 'Көп жазудың қажеті жоқ — бір сөйлем күнге деген көзқарасыңызды өзгерте алады.', false), ('es', 'home.motivation.card2_description', 'No es necesario escribir mucho: una frase puede cambiar tu perspectiva del día.', false), ('de', 'home.motivation.card2_description', 'Du musst nicht viel schreiben — ein Satz kann deine Sicht auf den Tag verändern.', false), ('fr', 'home.motivation.card2_description', 'Pas besoin d\'écrire beaucoup — une phrase peut changer votre vision de la journée.', false), ('zh', 'home.motivation.card2_description', '你不必写很多——一句话就能改变你对这一天的看法。', false), ('ja', 'home.motivation.card2_description', 'たくさん書く必要はありません — 一つのフレーズがその日の見方を変えることができます。', false), ('ka', 'home.motivation.card2_description', 'არ არის საჭირო ბევრი დაწერა — ერთი ფრაზა შეიძლება შეცვალოს თქვენი ხედვა დღის შესახებ.', false),
('ru', 'home.motivation.card3_title', 'Запиши момент благодарности', false), ('en', 'home.motivation.card3_title', 'Write down a moment of gratitude', false), ('kk', 'home.motivation.card3_title', 'Алғыс сәтін жазыңыз', false), ('es', 'home.motivation.card3_title', 'Escribe un momento de gratitud', false), ('de', 'home.motivation.card3_title', 'Schreibe einen Moment der Dankbarkeit auf', false), ('fr', 'home.motivation.card3_title', 'Notez un moment de gratitude', false), ('zh', 'home.motivation.card3_title', '记下感恩的时刻', false), ('ja', 'home.motivation.card3_title', '感謝の瞬間を書き留めましょう', false), ('ka', 'home.motivation.card3_title', 'ჩაწერეთ მადლიერების მომენტი', false),
('ru', 'home.motivation.card3_description', 'Почувствуй лёгкость, когда замечаешь хорошее в своей жизни. Это путь к счастью.', false), ('en', 'home.motivation.card3_description', 'Feel the lightness when you notice the good in your life. This is the path to happiness.', false), ('kk', 'home.motivation.card3_description', 'Өміріңіздегі жақсыны байқаған кезде жеңілдікті сезініңіз. Бұл бақытқа апаратын жол.', false), ('es', 'home.motivation.card3_description', 'Siente la ligereza cuando notas lo bueno en tu vida. Este es el camino a la felicidad.', false), ('de', 'home.motivation.card3_description', 'Fühle die Leichtigkeit, wenn du das Gute in deinem Leben bemerkst. Das ist der Weg zum Glück.', false), ('fr', 'home.motivation.card3_description', 'Ressentez la légèreté lorsque vous remarquez le bien dans votre vie. C\'est le chemin vers le bonheur.', false), ('zh', 'home.motivation.card3_description', '当你注意到生活中的美好时，感受那份轻松。这是通往幸福的道路。', false), ('ja', 'home.motivation.card3_description', '人生の良いことに気づいたとき、軽さを感じてください。これが幸せへの道です。', false), ('ka', 'home.motivation.card3_description', 'იგრძენით სიმსუბუქე, როდესაც ამჩნევთ კარგს თქვენს ცხოვრებაში. ეს არის გზა ბედნიერებისკენ.', false),

-- Main Screen - Input Placeholder (1 key × 9 languages = 9 translations)
('ru', 'home.input.placeholder', 'Опиши главную мысль, момент, благодарность', false), ('en', 'home.input.placeholder', 'Describe the main thought, moment, gratitude', false), ('kk', 'home.input.placeholder', 'Басты ойды, сәтті, алғысты сипаттаңыз', false), ('es', 'home.input.placeholder', 'Describe el pensamiento principal, momento, gratitud', false), ('de', 'home.input.placeholder', 'Beschreibe den Hauptgedanken, Moment, Dankbarkeit', false), ('fr', 'home.input.placeholder', 'Décrivez la pensée principale, le moment, la gratitude', false), ('zh', 'home.input.placeholder', '描述主要想法、时刻、感激', false), ('ja', 'home.input.placeholder', '主な考え、瞬間、感謝を説明してください', false), ('ka', 'home.input.placeholder', 'აღწერეთ მთავარი აზრი, მომენტი, მადლიერება', false),

-- History Screen - Empty State Fix (1 key × 9 languages = 9 translations)
('ru', 'history.empty_state', 'Записи не найдены', false), ('en', 'history.empty_state', 'No entries found', false), ('kk', 'history.empty_state', 'Жазбалар табылмады', false), ('es', 'history.empty_state', 'No se encontraron entradas', false), ('de', 'history.empty_state', 'Keine Einträge gefunden', false), ('fr', 'history.empty_state', 'Aucune entrée trouvée', false), ('zh', 'history.empty_state', '未找到条目', false), ('ja', 'history.empty_state', 'エントリーが見つかりません', false), ('ka', 'history.empty_state', 'ჩანაწერები არ მოიძებნა', false),

-- Achievements Screen - Stats (7 keys × 9 languages = 63 translations)
('ru', 'achievements.stats.entries', 'Записей', false), ('en', 'achievements.stats.entries', 'Entries', false), ('kk', 'achievements.stats.entries', 'Жазбалар', false), ('es', 'achievements.stats.entries', 'Entradas', false), ('de', 'achievements.stats.entries', 'Einträge', false), ('fr', 'achievements.stats.entries', 'Entrées', false), ('zh', 'achievements.stats.entries', '条目', false), ('ja', 'achievements.stats.entries', 'エントリー', false), ('ka', 'achievements.stats.entries', 'ჩანაწერები', false),
('ru', 'achievements.stats.awards', 'Наград', false), ('en', 'achievements.stats.awards', 'Awards', false), ('kk', 'achievements.stats.awards', 'Марапаттар', false), ('es', 'achievements.stats.awards', 'Premios', false), ('de', 'achievements.stats.awards', 'Auszeichnungen', false), ('fr', 'achievements.stats.awards', 'Récompenses', false), ('zh', 'achievements.stats.awards', '奖励', false), ('ja', 'achievements.stats.awards', '賞', false), ('ka', 'achievements.stats.awards', 'ჯილდოები', false),
('ru', 'achievements.stats.days_in_row', 'Дней подряд', false), ('en', 'achievements.stats.days_in_row', 'Days in a row', false), ('kk', 'achievements.stats.days_in_row', 'Күн қатарынан', false), ('es', 'achievements.stats.days_in_row', 'Días seguidos', false), ('de', 'achievements.stats.days_in_row', 'Tage hintereinander', false), ('fr', 'achievements.stats.days_in_row', 'Jours consécutifs', false), ('zh', 'achievements.stats.days_in_row', '连续天数', false), ('ja', 'achievements.stats.days_in_row', '連続日数', false), ('ka', 'achievements.stats.days_in_row', 'დღეები ზედიზედ', false),
('ru', 'achievements.stats.record', 'Рекорд', false), ('en', 'achievements.stats.record', 'Record', false), ('kk', 'achievements.stats.record', 'Рекорд', false), ('es', 'achievements.stats.record', 'Récord', false), ('de', 'achievements.stats.record', 'Rekord', false), ('fr', 'achievements.stats.record', 'Record', false), ('zh', 'achievements.stats.record', '记录', false), ('ja', 'achievements.stats.record', '記録', false), ('ka', 'achievements.stats.record', 'რეკორდი', false),
('ru', 'achievements.stats.to_level', 'До уровня ', false), ('en', 'achievements.stats.to_level', 'To level ', false), ('kk', 'achievements.stats.to_level', 'Деңгейге дейін ', false), ('es', 'achievements.stats.to_level', 'Hasta nivel ', false), ('de', 'achievements.stats.to_level', 'Bis Level ', false), ('fr', 'achievements.stats.to_level', 'Jusqu\'au niveau ', false), ('zh', 'achievements.stats.to_level', '到等级 ', false), ('ja', 'achievements.stats.to_level', 'レベルまで ', false), ('ka', 'achievements.stats.to_level', 'დონემდე ', false),
('ru', 'achievements.filter.all', 'Все', false), ('en', 'achievements.filter.all', 'All', false), ('kk', 'achievements.filter.all', 'Барлығы', false), ('es', 'achievements.filter.all', 'Todos', false), ('de', 'achievements.filter.all', 'Alle', false), ('fr', 'achievements.filter.all', 'Tous', false), ('zh', 'achievements.filter.all', '全部', false), ('ja', 'achievements.filter.all', 'すべて', false), ('ka', 'achievements.filter.all', 'ყველა', false),
('ru', 'achievements.filter.received', 'Полученные', false), ('en', 'achievements.filter.received', 'Received', false), ('kk', 'achievements.filter.received', 'Алынған', false), ('es', 'achievements.filter.received', 'Recibidos', false), ('de', 'achievements.filter.received', 'Erhalten', false), ('fr', 'achievements.filter.received', 'Reçus', false), ('zh', 'achievements.filter.received', '已获得', false), ('ja', 'achievements.filter.received', '受け取った', false), ('ka', 'achievements.filter.received', 'მიღებული', false),

-- Reports Screen - Headers & Buttons (5 keys × 9 languages = 45 translations)
('ru', 'reports.open_reports', 'Открыть отчёты', false), ('en', 'reports.open_reports', 'Open reports', false), ('kk', 'reports.open_reports', 'Есептерді ашу', false), ('es', 'reports.open_reports', 'Abrir informes', false), ('de', 'reports.open_reports', 'Berichte öffnen', false), ('fr', 'reports.open_reports', 'Ouvrir les rapports', false), ('zh', 'reports.open_reports', '打开报告', false), ('ja', 'reports.open_reports', 'レポートを開く', false), ('ka', 'reports.open_reports', 'ანგარიშების გახსნა', false),
('ru', 'reports.month_report', 'Отчет за {month} {year} г.', false), ('en', 'reports.month_report', 'Report for {month} {year}', false), ('kk', 'reports.month_report', '{year} ж. {month} есебі', false), ('es', 'reports.month_report', 'Informe de {month} {year}', false), ('de', 'reports.month_report', 'Bericht für {month} {year}', false), ('fr', 'reports.month_report', 'Rapport pour {month} {year}', false), ('zh', 'reports.month_report', '{year}年{month}报告', false), ('ja', 'reports.month_report', '{year}年{month}のレポート', false), ('ka', 'reports.month_report', 'ანგარიში {month} {year}', false),
('ru', 'reports.ai_analysis', 'Персональный анализ от AI', false), ('en', 'reports.ai_analysis', 'Personal analysis from AI', false), ('kk', 'reports.ai_analysis', 'AI-дан жеке талдау', false), ('es', 'reports.ai_analysis', 'Análisis personal de AI', false), ('de', 'reports.ai_analysis', 'Persönliche Analyse von AI', false), ('fr', 'reports.ai_analysis', 'Analyse personnelle par IA', false), ('zh', 'reports.ai_analysis', 'AI个人分析', false), ('ja', 'reports.ai_analysis', 'AIによる個人分析', false), ('ka', 'reports.ai_analysis', 'პერსონალური ანალიზი AI-სგან', false),
('ru', 'reports.premium_badge', 'Премиум', false), ('en', 'reports.premium_badge', 'Premium', false), ('kk', 'reports.premium_badge', 'Premium', false), ('es', 'reports.premium_badge', 'Premium', false), ('de', 'reports.premium_badge', 'Premium', false), ('fr', 'reports.premium_badge', 'Premium', false), ('zh', 'reports.premium_badge', '高级', false), ('ja', 'reports.premium_badge', 'プレミアム', false), ('ka', 'reports.premium_badge', 'პრემიუმი', false),
('ru', 'reports.books_description', 'Создавай книги на основе дневника и возвращайся к ним в любой момент на своей полке.', false), ('en', 'reports.books_description', 'Create books based on your diary and return to them anytime on your shelf.', false), ('kk', 'reports.books_description', 'Күнделік негізінде кітаптар жасаңыз және оларға кез келген уақытта сөреңізден қайта оралыңыз.', false), ('es', 'reports.books_description', 'Crea libros basados en tu diario y vuelve a ellos en cualquier momento en tu estante.', false), ('de', 'reports.books_description', 'Erstelle Bücher basierend auf deinem Tagebuch und kehre jederzeit in deinem Regal zu ihnen zurück.', false), ('fr', 'reports.books_description', 'Créez des livres basés sur votre journal et revenez-y à tout moment sur votre étagère.', false), ('zh', 'reports.books_description', '根据您的日记创建书籍，并随时在您的书架上返回它们。', false), ('ja', 'reports.books_description', '日記に基づいて本を作成し、いつでも本棚で戻ることができます。', false), ('ka', 'reports.books_description', 'შექმენით წიგნები თქვენი დღიურის საფუძველზე და დაუბრუნდით მათ ნებისმიერ დროს თქვენს თაროზე.', false),

-- WelcomeTrial Modal (10 keys × 9 languages = 90 translations)
('ru', 'welcomeTrial.title', 'Добро пожаловать в UNITY!', false), ('en', 'welcomeTrial.title', 'Welcome to UNITY!', false), ('kk', 'welcomeTrial.title', 'UNITY-ге қош келдіңіз!', false), ('es', 'welcomeTrial.title', '¡Bienvenido a UNITY!', false), ('de', 'welcomeTrial.title', 'Willkommen bei UNITY!', false), ('fr', 'welcomeTrial.title', 'Bienvenue sur UNITY!', false), ('zh', 'welcomeTrial.title', '欢迎来到UNITY！', false), ('ja', 'welcomeTrial.title', 'UNITYへようこそ！', false), ('ka', 'welcomeTrial.title', 'კეთილი იყოს თქვენი მობრძანება UNITY-ში!', false),
('ru', 'welcomeTrial.youReceived', 'Вы получили', false), ('en', 'welcomeTrial.youReceived', 'You received', false), ('kk', 'welcomeTrial.youReceived', 'Сіз алдыңыз', false), ('es', 'welcomeTrial.youReceived', 'Has recibido', false), ('de', 'welcomeTrial.youReceived', 'Sie haben erhalten', false), ('fr', 'welcomeTrial.youReceived', 'Vous avez reçu', false), ('zh', 'welcomeTrial.youReceived', '您收到了', false), ('ja', 'welcomeTrial.youReceived', 'あなたは受け取りました', false), ('ka', 'welcomeTrial.youReceived', 'თქვენ მიიღეთ', false),
('ru', 'welcomeTrial.premiumDays', '14 дней Premium', false), ('en', 'welcomeTrial.premiumDays', '14 days Premium', false), ('kk', 'welcomeTrial.premiumDays', '14 күн Premium', false), ('es', 'welcomeTrial.premiumDays', '14 días Premium', false), ('de', 'welcomeTrial.premiumDays', '14 Tage Premium', false), ('fr', 'welcomeTrial.premiumDays', '14 jours Premium', false), ('zh', 'welcomeTrial.premiumDays', '14天高级版', false), ('ja', 'welcomeTrial.premiumDays', '14日間プレミアム', false), ('ka', 'welcomeTrial.premiumDays', '14 დღე Premium', false),
('ru', 'welcomeTrial.free', 'бесплатно', false), ('en', 'welcomeTrial.free', 'free', false), ('kk', 'welcomeTrial.free', 'тегін', false), ('es', 'welcomeTrial.free', 'gratis', false), ('de', 'welcomeTrial.free', 'kostenlos', false), ('fr', 'welcomeTrial.free', 'gratuit', false), ('zh', 'welcomeTrial.free', '免费', false), ('ja', 'welcomeTrial.free', '無料', false), ('ka', 'welcomeTrial.free', 'უფასოდ', false),
('ru', 'welcomeTrial.startUsing', 'Начать использовать', false), ('en', 'welcomeTrial.startUsing', 'Start using', false), ('kk', 'welcomeTrial.startUsing', 'Пайдалануды бастау', false), ('es', 'welcomeTrial.startUsing', 'Empezar a usar', false), ('de', 'welcomeTrial.startUsing', 'Beginnen zu verwenden', false), ('fr', 'welcomeTrial.startUsing', 'Commencer à utiliser', false), ('zh', 'welcomeTrial.startUsing', '开始使用', false), ('ja', 'welcomeTrial.startUsing', '使用を開始', false), ('ka', 'welcomeTrial.startUsing', 'გამოყენების დაწყება', false),
('ru', 'welcomeTrial.feature.aiAnalysis.title', 'AI анализ записей', false), ('en', 'welcomeTrial.feature.aiAnalysis.title', 'AI entry analysis', false), ('kk', 'welcomeTrial.feature.aiAnalysis.title', 'AI жазбаларды талдау', false), ('es', 'welcomeTrial.feature.aiAnalysis.title', 'Análisis AI de entradas', false), ('de', 'welcomeTrial.feature.aiAnalysis.title', 'KI-Eintragsanalyse', false), ('fr', 'welcomeTrial.feature.aiAnalysis.title', 'Analyse IA des entrées', false), ('zh', 'welcomeTrial.feature.aiAnalysis.title', 'AI条目分析', false), ('ja', 'welcomeTrial.feature.aiAnalysis.title', 'AIエントリー分析', false), ('ka', 'welcomeTrial.feature.aiAnalysis.title', 'AI ჩანაწერების ანალიზი', false),
('ru', 'welcomeTrial.feature.aiAnalysis.description', 'Умный анализ ваших мыслей и эмоций', false), ('en', 'welcomeTrial.feature.aiAnalysis.description', 'Smart analysis of your thoughts and emotions', false), ('kk', 'welcomeTrial.feature.aiAnalysis.description', 'Сіздің ойларыңыз бен эмоцияларыңызды ақылды талдау', false), ('es', 'welcomeTrial.feature.aiAnalysis.description', 'Análisis inteligente de tus pensamientos y emociones', false), ('de', 'welcomeTrial.feature.aiAnalysis.description', 'Intelligente Analyse Ihrer Gedanken und Emotionen', false), ('fr', 'welcomeTrial.feature.aiAnalysis.description', 'Analyse intelligente de vos pensées et émotions', false), ('zh', 'welcomeTrial.feature.aiAnalysis.description', '智能分析您的想法和情绪', false), ('ja', 'welcomeTrial.feature.aiAnalysis.description', 'あなたの考えと感情のスマート分析', false), ('ka', 'welcomeTrial.feature.aiAnalysis.description', 'თქვენი აზრებისა და ემოციების ჭკვიანი ანალიზი', false),
('ru', 'welcomeTrial.feature.unlimitedEntries.title', 'Неограниченные записи', false), ('en', 'welcomeTrial.feature.unlimitedEntries.title', 'Unlimited entries', false), ('kk', 'welcomeTrial.feature.unlimitedEntries.title', 'Шексіз жазбалар', false), ('es', 'welcomeTrial.feature.unlimitedEntries.title', 'Entradas ilimitadas', false), ('de', 'welcomeTrial.feature.unlimitedEntries.title', 'Unbegrenzte Einträge', false), ('fr', 'welcomeTrial.feature.unlimitedEntries.title', 'Entrées illimitées', false), ('zh', 'welcomeTrial.feature.unlimitedEntries.title', '无限条目', false), ('ja', 'welcomeTrial.feature.unlimitedEntries.title', '無制限エントリー', false), ('ka', 'welcomeTrial.feature.unlimitedEntries.title', 'შეუზღუდავი ჩანაწერები', false),
('ru', 'welcomeTrial.feature.unlimitedEntries.description', 'Создавайте сколько угодно записей в месяц', false), ('en', 'welcomeTrial.feature.unlimitedEntries.description', 'Create as many entries as you want per month', false), ('kk', 'welcomeTrial.feature.unlimitedEntries.description', 'Айына қанша қаласаңыз сонша жазба жасаңыз', false), ('es', 'welcomeTrial.feature.unlimitedEntries.description', 'Crea tantas entradas como quieras al mes', false), ('de', 'welcomeTrial.feature.unlimitedEntries.description', 'Erstellen Sie so viele Einträge wie Sie möchten pro Monat', false), ('fr', 'welcomeTrial.feature.unlimitedEntries.description', 'Créez autant d\'entrées que vous le souhaitez par mois', false), ('zh', 'welcomeTrial.feature.unlimitedEntries.description', '每月创建任意数量的条目', false), ('ja', 'welcomeTrial.feature.unlimitedEntries.description', '月に好きなだけエントリーを作成', false), ('ka', 'welcomeTrial.feature.unlimitedEntries.description', 'შექმენით რამდენიც გინდათ ჩანაწერი თვეში', false),
('ru', 'welcomeTrial.feature.offline.title', 'Offline режим', false), ('en', 'welcomeTrial.feature.offline.title', 'Offline mode', false), ('kk', 'welcomeTrial.feature.offline.title', 'Offline режимі', false), ('es', 'welcomeTrial.feature.offline.title', 'Modo offline', false), ('de', 'welcomeTrial.feature.offline.title', 'Offline-Modus', false), ('fr', 'welcomeTrial.feature.offline.title', 'Mode hors ligne', false), ('zh', 'welcomeTrial.feature.offline.title', '离线模式', false), ('ja', 'welcomeTrial.feature.offline.title', 'オフラインモード', false), ('ka', 'welcomeTrial.feature.offline.title', 'ოფლაინ რეჟიმი', false),
('ru', 'welcomeTrial.feature.offline.description', 'Работайте без интернета с автосинхронизацией', false), ('en', 'welcomeTrial.feature.offline.description', 'Work without internet with auto-sync', false), ('kk', 'welcomeTrial.feature.offline.description', 'Интернетсіз жұмыс істеңіз, автосинхрондаумен', false), ('es', 'welcomeTrial.feature.offline.description', 'Trabaja sin internet con sincronización automática', false), ('de', 'welcomeTrial.feature.offline.description', 'Arbeiten Sie ohne Internet mit Auto-Sync', false), ('fr', 'welcomeTrial.feature.offline.description', 'Travaillez sans internet avec synchronisation automatique', false), ('zh', 'welcomeTrial.feature.offline.description', '无需互联网即可工作，自动同步', false), ('ja', 'welcomeTrial.feature.offline.description', 'インターネットなしで作業、自動同期', false), ('ka', 'welcomeTrial.feature.offline.description', 'იმუშავეთ ინტერნეტის გარეშე ავტო-სინქრონიზაციით', false),
('ru', 'welcomeTrial.feature.pdfBooks.title', 'PDF-книги', false), ('en', 'welcomeTrial.feature.pdfBooks.title', 'PDF books', false), ('kk', 'welcomeTrial.feature.pdfBooks.title', 'PDF-кітаптар', false), ('es', 'welcomeTrial.feature.pdfBooks.title', 'Libros PDF', false), ('de', 'welcomeTrial.feature.pdfBooks.title', 'PDF-Bücher', false), ('fr', 'welcomeTrial.feature.pdfBooks.title', 'Livres PDF', false), ('zh', 'welcomeTrial.feature.pdfBooks.title', 'PDF书籍', false), ('ja', 'welcomeTrial.feature.pdfBooks.title', 'PDF書籍', false), ('ka', 'welcomeTrial.feature.pdfBooks.title', 'PDF წიგნები', false),
('ru', 'welcomeTrial.feature.pdfBooks.description', 'Генерация красивых PDF с вашими записями', false), ('en', 'welcomeTrial.feature.pdfBooks.description', 'Generate beautiful PDFs with your entries', false), ('kk', 'welcomeTrial.feature.pdfBooks.description', 'Жазбаларыңызбен әдемі PDF жасау', false), ('es', 'welcomeTrial.feature.pdfBooks.description', 'Genera hermosos PDFs con tus entradas', false), ('de', 'welcomeTrial.feature.pdfBooks.description', 'Erstellen Sie schöne PDFs mit Ihren Einträgen', false), ('fr', 'welcomeTrial.feature.pdfBooks.description', 'Générez de beaux PDFs avec vos entrées', false), ('zh', 'welcomeTrial.feature.pdfBooks.description', '使用您的条目生成精美的PDF', false), ('ja', 'welcomeTrial.feature.pdfBooks.description', 'エントリーで美しいPDFを生成', false), ('ka', 'welcomeTrial.feature.pdfBooks.description', 'შექმენით ლამაზი PDF-ები თქვენი ჩანაწერებით', false),
('ru', 'welcomeTrial.feature.premiumThemes.title', 'Премиум-темы', false), ('en', 'welcomeTrial.feature.premiumThemes.title', 'Premium themes', false), ('kk', 'welcomeTrial.feature.premiumThemes.title', 'Премиум-темалар', false), ('es', 'welcomeTrial.feature.premiumThemes.title', 'Temas premium', false), ('de', 'welcomeTrial.feature.premiumThemes.title', 'Premium-Themen', false), ('fr', 'welcomeTrial.feature.premiumThemes.title', 'Thèmes premium', false), ('zh', 'welcomeTrial.feature.premiumThemes.title', '高级主题', false), ('ja', 'welcomeTrial.feature.premiumThemes.title', 'プレミアムテーマ', false), ('ka', 'welcomeTrial.feature.premiumThemes.title', 'პრემიუმ თემები', false),
('ru', 'welcomeTrial.feature.premiumThemes.description', 'Эксклюзивные цветовые схемы', false), ('en', 'welcomeTrial.feature.premiumThemes.description', 'Exclusive color schemes', false), ('kk', 'welcomeTrial.feature.premiumThemes.description', 'Эксклюзивті түс схемалары', false), ('es', 'welcomeTrial.feature.premiumThemes.description', 'Esquemas de color exclusivos', false), ('de', 'welcomeTrial.feature.premiumThemes.description', 'Exklusive Farbschemata', false), ('fr', 'welcomeTrial.feature.premiumThemes.description', 'Schémas de couleurs exclusifs', false), ('zh', 'welcomeTrial.feature.premiumThemes.description', '独家配色方案', false), ('ja', 'welcomeTrial.feature.premiumThemes.description', '独占カラースキーム', false), ('ka', 'welcomeTrial.feature.premiumThemes.description', 'ექსკლუზიური ფერის სქემები', false),
('ru', 'welcomeTrial.feature.analytics.title', 'Расширенная аналитика', false), ('en', 'welcomeTrial.feature.analytics.title', 'Advanced analytics', false), ('kk', 'welcomeTrial.feature.analytics.title', 'Кеңейтілген аналитика', false), ('es', 'welcomeTrial.feature.analytics.title', 'Análisis avanzado', false), ('de', 'welcomeTrial.feature.analytics.title', 'Erweiterte Analytik', false), ('fr', 'welcomeTrial.feature.analytics.title', 'Analytique avancée', false), ('zh', 'welcomeTrial.feature.analytics.title', '高级分析', false), ('ja', 'welcomeTrial.feature.analytics.title', '高度な分析', false), ('ka', 'welcomeTrial.feature.analytics.title', 'გაფართოებული ანალიტიკა', false),
('ru', 'welcomeTrial.feature.analytics.description', 'Детальные отчеты и графики прогресса', false), ('en', 'welcomeTrial.feature.analytics.description', 'Detailed reports and progress charts', false), ('kk', 'welcomeTrial.feature.analytics.description', 'Прогресстің толық есептері мен графиктері', false), ('es', 'welcomeTrial.feature.analytics.description', 'Informes detallados y gráficos de progreso', false), ('de', 'welcomeTrial.feature.analytics.description', 'Detaillierte Berichte und Fortschrittsdiagramme', false), ('fr', 'welcomeTrial.feature.analytics.description', 'Rapports détaillés et graphiques de progrès', false), ('zh', 'welcomeTrial.feature.analytics.description', '详细报告和进度图表', false), ('ja', 'welcomeTrial.feature.analytics.description', '詳細なレポートと進捗グラフ', false), ('ka', 'welcomeTrial.feature.analytics.description', 'დეტალური ანგარიშები და პროგრესის გრაფიკები', false),

-- Notifications Modal (8 keys × 9 languages = 72 translations)
('ru', 'notifications.modal.title', 'Включить уведомления?', false), ('en', 'notifications.modal.title', 'Enable notifications?', false), ('kk', 'notifications.modal.title', 'Хабарландыруларды қосу керек пе?', false), ('es', 'notifications.modal.title', '¿Activar notificaciones?', false), ('de', 'notifications.modal.title', 'Benachrichtigungen aktivieren?', false), ('fr', 'notifications.modal.title', 'Activer les notifications?', false), ('zh', 'notifications.modal.title', '启用通知？', false), ('ja', 'notifications.modal.title', '通知を有効にしますか？', false), ('ka', 'notifications.modal.title', 'შეტყობინებების ჩართვა?', false),
('ru', 'notifications.modal.description', 'Получайте напоминания о записях и мотивационные сообщения', false), ('en', 'notifications.modal.description', 'Get reminders about entries and motivational messages', false), ('kk', 'notifications.modal.description', 'Жазбалар туралы еске салғыштар мен мотивациялық хабарламалар алыңыз', false), ('es', 'notifications.modal.description', 'Recibe recordatorios sobre entradas y mensajes motivacionales', false), ('de', 'notifications.modal.description', 'Erhalten Sie Erinnerungen über Einträge und motivierende Nachrichten', false), ('fr', 'notifications.modal.description', 'Recevez des rappels sur les entrées et des messages motivants', false), ('zh', 'notifications.modal.description', '获取有关条目的提醒和激励消息', false), ('ja', 'notifications.modal.description', 'エントリーに関するリマインダーとモチベーションメッセージを受け取る', false), ('ka', 'notifications.modal.description', 'მიიღეთ შეხსენებები ჩანაწერების შესახებ და მოტივაციური შეტყობინებები', false),
('ru', 'notifications.modal.whenRemind', 'Когда напоминать?', false), ('en', 'notifications.modal.whenRemind', 'When to remind?', false), ('kk', 'notifications.modal.whenRemind', 'Қашан еске салу керек?', false), ('es', 'notifications.modal.whenRemind', '¿Cuándo recordar?', false), ('de', 'notifications.modal.whenRemind', 'Wann erinnern?', false), ('fr', 'notifications.modal.whenRemind', 'Quand rappeler?', false), ('zh', 'notifications.modal.whenRemind', '何时提醒？', false), ('ja', 'notifications.modal.whenRemind', 'いつリマインドしますか？', false), ('ka', 'notifications.modal.whenRemind', 'როდის შეახსენოთ?', false),
('ru', 'notifications.time.morning', 'Утром', false), ('en', 'notifications.time.morning', 'Morning', false), ('kk', 'notifications.time.morning', 'Таңертең', false), ('es', 'notifications.time.morning', 'Mañana', false), ('de', 'notifications.time.morning', 'Morgen', false), ('fr', 'notifications.time.morning', 'Matin', false), ('zh', 'notifications.time.morning', '早上', false), ('ja', 'notifications.time.morning', '朝', false), ('ka', 'notifications.time.morning', 'დილით', false),
('ru', 'notifications.time.evening', 'Вечером', false), ('en', 'notifications.time.evening', 'Evening', false), ('kk', 'notifications.time.evening', 'Кешке', false), ('es', 'notifications.time.evening', 'Noche', false), ('de', 'notifications.time.evening', 'Abend', false), ('fr', 'notifications.time.evening', 'Soir', false), ('zh', 'notifications.time.evening', '晚上', false), ('ja', 'notifications.time.evening', '夕方', false), ('ka', 'notifications.time.evening', 'საღამოს', false),
('ru', 'notifications.button.enable', 'Включить', false), ('en', 'notifications.button.enable', 'Enable', false), ('kk', 'notifications.button.enable', 'Қосу', false), ('es', 'notifications.button.enable', 'Activar', false), ('de', 'notifications.button.enable', 'Aktivieren', false), ('fr', 'notifications.button.enable', 'Activer', false), ('zh', 'notifications.button.enable', '启用', false), ('ja', 'notifications.button.enable', '有効にする', false), ('ka', 'notifications.button.enable', 'ჩართვა', false),
('ru', 'notifications.button.later', 'Позже', false), ('en', 'notifications.button.later', 'Later', false), ('kk', 'notifications.button.later', 'Кейінірек', false), ('es', 'notifications.button.later', 'Más tarde', false), ('de', 'notifications.button.later', 'Später', false), ('fr', 'notifications.button.later', 'Plus tard', false), ('zh', 'notifications.button.later', '稍后', false), ('ja', 'notifications.button.later', '後で', false), ('ka', 'notifications.button.later', 'მოგვიანებით', false),
('ru', 'notifications.button.enabling', 'Включение...', false), ('en', 'notifications.button.enabling', 'Enabling...', false), ('kk', 'notifications.button.enabling', 'Қосылуда...', false), ('es', 'notifications.button.enabling', 'Activando...', false), ('de', 'notifications.button.enabling', 'Aktivierung...', false), ('fr', 'notifications.button.enabling', 'Activation...', false), ('zh', 'notifications.button.enabling', '启用中...', false), ('ja', 'notifications.button.enabling', '有効化中...', false), ('ka', 'notifications.button.enabling', 'ჩართვა...', false),

-- Navigation (5 keys × 9 languages = 45 translations)
('ru', 'home', 'Главная', false), ('en', 'home', 'Home', false), ('kk', 'home', 'Басты бет', false), ('es', 'home', 'Inicio', false), ('de', 'home', 'Startseite', false), ('fr', 'home', 'Accueil', false), ('zh', 'home', '首页', false), ('ja', 'home', 'ホーム', false), ('ka', 'home', 'მთავარი', false),
('ru', 'history', 'История', false), ('en', 'history', 'History', false), ('kk', 'history', 'Тарих', false), ('es', 'history', 'Historial', false), ('de', 'history', 'Verlauf', false), ('fr', 'history', 'Historique', false), ('zh', 'history', '历史', false), ('ja', 'history', '履歴', false), ('ka', 'history', 'ისტორია', false),
('ru', 'achievements', 'Достижения', false), ('en', 'achievements', 'Achievements', false), ('kk', 'achievements', 'Жетістіктер', false), ('es', 'achievements', 'Logros', false), ('de', 'achievements', 'Erfolge', false), ('fr', 'achievements', 'Réalisations', false), ('zh', 'achievements', '成就', false), ('ja', 'achievements', '実績', false), ('ka', 'achievements', 'მიღწევები', false),
('ru', 'reports', 'Отчеты', false), ('en', 'reports', 'Reports', false), ('kk', 'reports', 'Есептер', false), ('es', 'reports', 'Informes', false), ('de', 'reports', 'Berichte', false), ('fr', 'reports', 'Rapports', false), ('zh', 'reports', '报告', false), ('ja', 'reports', 'レポート', false), ('ka', 'reports', 'ანგარიშები', false),
('ru', 'settings', 'Настройки', false), ('en', 'settings', 'Settings', false), ('kk', 'settings', 'Баптаулар', false), ('es', 'settings', 'Configuración', false), ('de', 'settings', 'Einstellungen', false), ('fr', 'settings', 'Paramètres', false), ('zh', 'settings', '设置', false), ('ja', 'settings', '設定', false), ('ka', 'settings', 'პარამეტრები', false),

-- Premium Modal - New Keys (4 keys × 9 languages = 36 translations)
('ru', 'premium.header.title_short', 'Premium', false), ('en', 'premium.header.title_short', 'Premium', false), ('kk', 'premium.header.title_short', 'Premium', false), ('es', 'premium.header.title_short', 'Premium', false), ('de', 'premium.header.title_short', 'Premium', false), ('fr', 'premium.header.title_short', 'Premium', false), ('zh', 'premium.header.title_short', '高级版', false), ('ja', 'premium.header.title_short', 'プレミアム', false), ('ka', 'premium.header.title_short', 'პრემიუმი', false),
('ru', 'premium.pricing.yearly_short', '$49.99/год (-17%)', false), ('en', 'premium.pricing.yearly_short', '$49.99/year (-17%)', false), ('kk', 'premium.pricing.yearly_short', '$49.99/жыл (-17%)', false), ('es', 'premium.pricing.yearly_short', '$49.99/año (-17%)', false), ('de', 'premium.pricing.yearly_short', '$49.99/Jahr (-17%)', false), ('fr', 'premium.pricing.yearly_short', '$49.99/an (-17%)', false), ('zh', 'premium.pricing.yearly_short', '$49.99/年 (-17%)', false), ('ja', 'premium.pricing.yearly_short', '$49.99/年 (-17%)', false), ('ka', 'premium.pricing.yearly_short', '$49.99/წელი (-17%)', false),
('ru', 'premium.features.title', 'Что входит:', false), ('en', 'premium.features.title', 'What\'s included:', false), ('kk', 'premium.features.title', 'Не кіреді:', false), ('es', 'premium.features.title', 'Qué incluye:', false), ('de', 'premium.features.title', 'Was ist enthalten:', false), ('fr', 'premium.features.title', 'Ce qui est inclus:', false), ('zh', 'premium.features.title', '包含内容：', false), ('ja', 'premium.features.title', '含まれるもの：', false), ('ka', 'premium.features.title', 'რა შედის:', false),
('ru', 'premium.footer.trial_short', '✨ 7 дней бесплатно', false), ('en', 'premium.footer.trial_short', '✨ 7 days free', false), ('kk', 'premium.footer.trial_short', '✨ 7 күн тегін', false), ('es', 'premium.footer.trial_short', '✨ 7 días gratis', false), ('de', 'premium.footer.trial_short', '✨ 7 Tage kostenlos', false), ('fr', 'premium.footer.trial_short', '✨ 7 jours gratuits', false), ('zh', 'premium.footer.trial_short', '✨ 7天免费', false), ('ja', 'premium.footer.trial_short', '✨ 7日間無料', false), ('ka', 'premium.footer.trial_short', '✨ 7 დღე უფასოდ', false)
ON CONFLICT (lang_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value, updated_at = NOW();

