-- Add Russian translations for achievement keys
-- Migration: 20251121000002_add_achievement_keys_ru.sql
-- Description: Add missing achievement translation keys to Russian language
-- These keys exist in Kazakh but are missing in Russian

INSERT INTO translations (lang_code, translation_key, translation_value) VALUES
-- COMMON ACHIEVEMENTS
('ru', 'achievement.first_entry.name', 'Первые шаги'),
('ru', 'achievement.first_entry.description', 'Создайте вашу первую запись'),
('ru', 'achievement.entries_5.name', 'Начало пути'),
('ru', 'achievement.entries_5.description', 'Создайте 5 записей'),
('ru', 'achievement.entries_10.name', 'Привычка формируется'),
('ru', 'achievement.entries_10.description', 'Создайте 10 записей'),
('ru', 'achievement.streak_3.name', 'Три дня подряд'),
('ru', 'achievement.streak_3.description', 'Создавайте записи 3 дня подряд'),
('ru', 'achievement.streak_7.name', 'Сила недели'),
('ru', 'achievement.streak_7.description', 'Создавайте записи 7 дней подряд'),
('ru', 'achievement.category_family_5.name', 'Семейные ценности'),
('ru', 'achievement.category_family_5.description', 'Создайте 5 записей о семье'),
('ru', 'achievement.category_health_5.name', 'Забота о себе'),
('ru', 'achievement.category_health_5.description', 'Создайте 5 записей о здоровье'),
('ru', 'achievement.category_work_5.name', 'Профессиональный рост'),
('ru', 'achievement.category_work_5.description', 'Создайте 5 записей о работе'),
('ru', 'achievement.category_finance_5.name', 'Финансовая осознанность'),
('ru', 'achievement.category_finance_5.description', 'Создайте 5 записей о финансах'),
('ru', 'achievement.category_growth_5.name', 'Путь развития'),
('ru', 'achievement.category_growth_5.description', 'Создайте 5 записей о личном росте'),
('ru', 'achievement.category_creativity_5.name', 'Творческое начало'),
('ru', 'achievement.category_creativity_5.description', 'Создайте 5 записей о творчестве'),
('ru', 'achievement.category_relationships_5.name', 'Связи важны'),
('ru', 'achievement.category_relationships_5.description', 'Создайте 5 записей об отношениях'),
('ru', 'achievement.category_gratitude_5.name', 'Первые шаги благодарности'),
('ru', 'achievement.category_gratitude_5.description', 'Создайте 5 записей о благодарности'),
('ru', 'achievement.emotional_first_steps.name', 'Первые эмоции'),
('ru', 'achievement.emotional_first_steps.description', 'Создайте записи с 3 разными настроениями'),

-- RARE ACHIEVEMENTS
('ru', 'achievement.entries_25.name', 'Четверть сотни'),
('ru', 'achievement.entries_25.description', 'Создайте 25 записей'),
('ru', 'achievement.entries_50.name', 'Пятьдесят побед'),
('ru', 'achievement.entries_50.description', 'Создайте 50 записей'),
('ru', 'achievement.streak_14.name', 'Сила двух недель'),
('ru', 'achievement.streak_14.description', 'Создавайте записи 14 дней подряд'),
('ru', 'achievement.streak_30.name', 'Месячная стабильность'),
('ru', 'achievement.streak_30.description', 'Создавайте записи 30 дней подряд'),
('ru', 'achievement.achievements_5.name', 'Пять побед'),
('ru', 'achievement.achievements_5.description', 'Отметьте 5 достижений'),
('ru', 'achievement.achievements_10.name', 'Десять побед'),
('ru', 'achievement.achievements_10.description', 'Отметьте 10 достижений'),
('ru', 'achievement.category_family_20.name', 'Семья - главное'),
('ru', 'achievement.category_family_20.description', 'Создайте 20 записей о семье'),
('ru', 'achievement.category_health_20.name', 'Здоровый образ жизни'),
('ru', 'achievement.category_health_20.description', 'Создайте 20 записей о здоровье'),
('ru', 'achievement.category_gratitude_10.name', 'Благодарное сердце'),
('ru', 'achievement.category_gratitude_10.description', 'Создайте 10 записей о благодарности'),
('ru', 'achievement.category_finance_20.name', 'Финансовый контроль'),
('ru', 'achievement.category_finance_20.description', 'Создайте 20 записей о финансах'),
('ru', 'achievement.category_growth_20.name', 'Мастер роста'),
('ru', 'achievement.category_growth_20.description', 'Создайте 20 записей о личном росте'),
('ru', 'achievement.category_creativity_20.name', 'Творческая душа'),
('ru', 'achievement.category_creativity_20.description', 'Создайте 20 записей о творчестве'),
('ru', 'achievement.category_relationships_20.name', 'Мастер отношений'),
('ru', 'achievement.category_relationships_20.description', 'Создайте 20 записей об отношениях'),
('ru', 'achievement.category_work_20.name', 'Фокус на работе'),
('ru', 'achievement.category_work_20.description', 'Создайте 20 записей о работе'),
('ru', 'achievement.honest_difficult_day.name', 'Правда в трудный день'),
('ru', 'achievement.honest_difficult_day.description', 'Честно напишите о трудном дне'),
('ru', 'achievement.emotional_variety.name', 'Разнообразие чувств'),
('ru', 'achievement.emotional_variety.description', 'Создайте записи с 6 разными настроениями'),
('ru', 'achievement.comeback_7.name', 'Возвращение'),
('ru', 'achievement.comeback_7.description', 'Вернитесь к записям после 7 дней перерыва'),

-- EPIC ACHIEVEMENTS
('ru', 'achievement.entries_100.name', 'Сто историй'),
('ru', 'achievement.entries_100.description', 'Создайте 100 записей'),
('ru', 'achievement.entries_250.name', 'Четверть тысячи'),
('ru', 'achievement.entries_250.description', 'Создайте 250 записей'),
('ru', 'achievement.streak_60.name', 'Сила двух месяцев'),
('ru', 'achievement.streak_60.description', 'Создавайте записи 60 дней подряд'),
('ru', 'achievement.streak_90.name', 'Девяностодневная стабильность'),
('ru', 'achievement.streak_90.description', 'Создавайте записи 90 дней подряд'),
('ru', 'achievement.achievements_25.name', 'Двадцать пять побед'),
('ru', 'achievement.achievements_25.description', 'Отметьте 25 достижений'),
('ru', 'achievement.achievements_50.name', 'Пятьдесят побед'),
('ru', 'achievement.achievements_50.description', 'Отметьте 50 достижений'),
('ru', 'achievement.category_family_50.name', 'Семейный мастер'),
('ru', 'achievement.category_family_50.description', 'Создайте 50 записей о семье'),
('ru', 'achievement.category_health_50.name', 'Мастер здоровья'),
('ru', 'achievement.category_health_50.description', 'Создайте 50 записей о здоровье'),
('ru', 'achievement.category_work_50.name', 'Профессионал'),
('ru', 'achievement.category_work_50.description', 'Создайте 50 записей о работе'),
('ru', 'achievement.emotional_balance.name', 'Эмоциональный баланс'),
('ru', 'achievement.emotional_balance.description', 'Создайте записи с 10 разными настроениями'),
('ru', 'achievement.comeback_30.name', 'Великое возвращение'),
('ru', 'achievement.comeback_30.description', 'Вернитесь к записям после 30 дней перерыва'),

-- LEGENDARY ACHIEVEMENTS
('ru', 'achievement.entries_500.name', 'Пятьсот историй'),
('ru', 'achievement.entries_500.description', 'Создайте 500 записей'),
('ru', 'achievement.entries_1000.name', 'Тысяча историй'),
('ru', 'achievement.entries_1000.description', 'Создайте 1000 записей'),
('ru', 'achievement.streak_180.name', 'Сила полугода'),
('ru', 'achievement.streak_180.description', 'Создавайте записи 180 дней подряд'),
('ru', 'achievement.streak_365.name', 'Годовая стабильность'),
('ru', 'achievement.streak_365.description', 'Создавайте записи 365 дней подряд'),
('ru', 'achievement.achievements_100.name', 'Сто побед'),
('ru', 'achievement.achievements_100.description', 'Отметьте 100 достижений'),
('ru', 'achievement.achievements_250.name', 'Легенда побед'),
('ru', 'achievement.achievements_250.description', 'Отметьте 250 достижений'),
('ru', 'achievement.category_family_100.name', 'Легенда семьи'),
('ru', 'achievement.category_family_100.description', 'Создайте 100 записей о семье'),
('ru', 'achievement.category_health_100.name', 'Легенда здоровья'),
('ru', 'achievement.category_health_100.description', 'Создайте 100 записей о здоровье'),
('ru', 'achievement.category_gratitude_50.name', 'Мастер благодарности'),
('ru', 'achievement.category_gratitude_50.description', 'Создайте 50 записей о благодарности'),
('ru', 'achievement.all_categories.name', 'Мастер всех сфер'),
('ru', 'achievement.all_categories.description', 'Создайте минимум 10 записей в каждой категории'),
('ru', 'achievement.year_complete.name', 'Год с UNITY'),
('ru', 'achievement.year_complete.description', 'Используйте UNITY весь год'),
('ru', 'achievement.first_honest_difficult_day.name', 'Первый честный трудный день'),
('ru', 'achievement.first_honest_difficult_day.description', 'Отметьте что хотя бы один день был трудным, но вы честно написали об этом')

ON CONFLICT (lang_code, translation_key) DO UPDATE
SET translation_value = EXCLUDED.translation_value,
    updated_at = NOW();

