-- Cleanup migration: Remove unused translation_keys table and key_id column
-- Migration: cleanup_translation_keys
-- Date: 2025-10-21
-- Author: AI Assistant (Augment Agent)
-- Reason: translation_keys table is not used by any Edge Functions or components
--         All translation logic uses only the translations table

-- 1. Remove foreign key constraint from translations table
ALTER TABLE translations DROP CONSTRAINT IF EXISTS translations_key_id_fkey;

-- 2. Remove key_id column from translations table
ALTER TABLE translations DROP COLUMN IF EXISTS key_id;

-- 3. Drop RLS policies for translation_keys table
DROP POLICY IF EXISTS "Everyone can read translation keys" ON translation_keys;
DROP POLICY IF EXISTS "Super admins can manage translation keys" ON translation_keys;

-- 4. Drop indexes for translation_keys table
DROP INDEX IF EXISTS idx_translation_keys_name;
DROP INDEX IF EXISTS idx_translation_keys_category;

-- 5. Drop translation_keys table
DROP TABLE IF EXISTS translation_keys;

-- 6. Add comment to translations table
COMMENT ON TABLE translations IS 'Translations for all languages. Uses translation_key as unique identifier (no separate keys table needed).';
COMMENT ON COLUMN translations.translation_key IS 'Unique key for translation (e.g., "welcome_title", "home", "settings")';
COMMENT ON COLUMN translations.lang_code IS 'Language code (e.g., "ru", "en", "es")';
COMMENT ON COLUMN translations.translation_value IS 'Translated text value';
COMMENT ON COLUMN translations.is_ai_translated IS 'Was this translation generated by AI?';
COMMENT ON COLUMN translations.confidence_score IS 'AI translation confidence score (0-1)';
COMMENT ON COLUMN translations.needs_review IS 'Does this translation need manual review?';

