-- Migration: Add PDF translations for books and reports
-- Date: 2025-11-21
-- Description: Добавляет переводы для всех текстов в PDF документах (книги и отчеты)

-- ============================================================================
-- PART 1: BOOKS PDF TRANSLATIONS
-- ============================================================================

INSERT INTO translations (lang_code, translation_key, translation_value) VALUES
-- Russian
('ru', 'books.pdf.prologue', 'Вступление'),
('ru', 'books.pdf.chapter', 'Глава'),
('ru', 'books.pdf.epilogue', 'Заключение'),

-- English
('en', 'books.pdf.prologue', 'Prologue'),
('en', 'books.pdf.chapter', 'Chapter'),
('en', 'books.pdf.epilogue', 'Epilogue'),

-- Spanish
('es', 'books.pdf.prologue', 'Prólogo'),
('es', 'books.pdf.chapter', 'Capítulo'),
('es', 'books.pdf.epilogue', 'Epílogo'),

-- German
('de', 'books.pdf.prologue', 'Prolog'),
('de', 'books.pdf.chapter', 'Kapitel'),
('de', 'books.pdf.epilogue', 'Epilog'),

-- French
('fr', 'books.pdf.prologue', 'Prologue'),
('fr', 'books.pdf.chapter', 'Chapitre'),
('fr', 'books.pdf.epilogue', 'Épilogue'),

-- Chinese
('zh', 'books.pdf.prologue', '序言'),
('zh', 'books.pdf.chapter', '章节'),
('zh', 'books.pdf.epilogue', '结语'),

-- Japanese
('ja', 'books.pdf.prologue', 'プロローグ'),
('ja', 'books.pdf.chapter', '章'),
('ja', 'books.pdf.epilogue', 'エピローグ'),

-- Georgian
('ka', 'books.pdf.prologue', 'პროლოგი'),
('ka', 'books.pdf.chapter', 'თავი'),
('ka', 'books.pdf.epilogue', 'ეპილოგი'),

-- Kazakh
('kk', 'books.pdf.prologue', 'Кіріспе'),
('kk', 'books.pdf.chapter', 'Тақырып'),
('kk', 'books.pdf.epilogue', 'Қорытынды')

ON CONFLICT (lang_code, translation_key) DO UPDATE
SET translation_value = EXCLUDED.translation_value,
    updated_at = NOW();

-- ============================================================================
-- PART 2: REPORTS PDF TRANSLATIONS
-- ============================================================================

INSERT INTO translations (lang_code, translation_key, translation_value) VALUES
-- Russian
('ru', 'reports.pdf.title', 'Отчет UNITY'),
('ru', 'reports.pdf.user', 'Пользователь'),
('ru', 'reports.pdf.statistics', 'Статистика'),
('ru', 'reports.pdf.entries', 'Записей'),
('ru', 'reports.pdf.per_day', 'В день'),
('ru', 'reports.pdf.achievements', 'Достижений'),
('ru', 'reports.pdf.mood', 'Настроение'),
('ru', 'reports.pdf.ai_analysis', 'AI Анализ'),
('ru', 'reports.pdf.entries_period', 'Записи за период'),
('ru', 'reports.pdf.achievement_badge', 'Достижение'),
('ru', 'reports.pdf.more_entries', '... и еще {count} записей'),
('ru', 'reports.pdf.generated_by', 'Сгенерировано UNITY'),
('ru', 'reports.pdf.weekly_report', 'Недельный отчет за'),
('ru', 'reports.pdf.monthly_report', 'Месячный отчет за'),

-- English
('en', 'reports.pdf.title', 'UNITY Report'),
('en', 'reports.pdf.user', 'User'),
('en', 'reports.pdf.statistics', 'Statistics'),
('en', 'reports.pdf.entries', 'Entries'),
('en', 'reports.pdf.per_day', 'Per day'),
('en', 'reports.pdf.achievements', 'Achievements'),
('en', 'reports.pdf.mood', 'Mood'),
('en', 'reports.pdf.ai_analysis', 'AI Analysis'),
('en', 'reports.pdf.entries_period', 'Entries for the period'),
('en', 'reports.pdf.achievement_badge', 'Achievement'),
('en', 'reports.pdf.more_entries', '... and {count} more entries'),
('en', 'reports.pdf.generated_by', 'Generated by UNITY'),
('en', 'reports.pdf.weekly_report', 'Weekly report for'),
('en', 'reports.pdf.monthly_report', 'Monthly report for'),

-- Spanish
('es', 'reports.pdf.title', 'Informe UNITY'),
('es', 'reports.pdf.user', 'Usuario'),
('es', 'reports.pdf.statistics', 'Estadísticas'),
('es', 'reports.pdf.entries', 'Entradas'),
('es', 'reports.pdf.per_day', 'Por día'),
('es', 'reports.pdf.achievements', 'Logros'),
('es', 'reports.pdf.mood', 'Estado de ánimo'),
('es', 'reports.pdf.ai_analysis', 'Análisis de IA'),
('es', 'reports.pdf.entries_period', 'Entradas del período'),
('es', 'reports.pdf.achievement_badge', 'Logro'),
('es', 'reports.pdf.more_entries', '... y {count} entradas más'),
('es', 'reports.pdf.generated_by', 'Generado por UNITY'),
('es', 'reports.pdf.weekly_report', 'Informe semanal de'),
('es', 'reports.pdf.monthly_report', 'Informe mensual de'),

-- German
('de', 'reports.pdf.title', 'UNITY Bericht'),
('de', 'reports.pdf.user', 'Benutzer'),
('de', 'reports.pdf.statistics', 'Statistiken'),
('de', 'reports.pdf.entries', 'Einträge'),
('de', 'reports.pdf.per_day', 'Pro Tag'),
('de', 'reports.pdf.achievements', 'Erfolge'),
('de', 'reports.pdf.mood', 'Stimmung'),
('de', 'reports.pdf.ai_analysis', 'KI-Analyse'),
('de', 'reports.pdf.entries_period', 'Einträge für den Zeitraum'),
('de', 'reports.pdf.achievement_badge', 'Erfolg'),
('de', 'reports.pdf.more_entries', '... und {count} weitere Einträge'),
('de', 'reports.pdf.generated_by', 'Generiert von UNITY'),
('de', 'reports.pdf.weekly_report', 'Wochenbericht für'),
('de', 'reports.pdf.monthly_report', 'Monatsbericht für'),

-- French
('fr', 'reports.pdf.title', 'Rapport UNITY'),
('fr', 'reports.pdf.user', 'Utilisateur'),
('fr', 'reports.pdf.statistics', 'Statistiques'),
('fr', 'reports.pdf.entries', 'Entrées'),
('fr', 'reports.pdf.per_day', 'Par jour'),
('fr', 'reports.pdf.achievements', 'Réalisations'),
('fr', 'reports.pdf.mood', 'Humeur'),
('fr', 'reports.pdf.ai_analysis', 'Analyse IA'),
('fr', 'reports.pdf.entries_period', 'Entrées pour la période'),
('fr', 'reports.pdf.achievement_badge', 'Réalisation'),
('fr', 'reports.pdf.more_entries', '... et {count} entrées de plus'),
('fr', 'reports.pdf.generated_by', 'Généré par UNITY'),
('fr', 'reports.pdf.weekly_report', 'Rapport hebdomadaire pour'),
('fr', 'reports.pdf.monthly_report', 'Rapport mensuel pour'),

-- Chinese
('zh', 'reports.pdf.title', 'UNITY 报告'),
('zh', 'reports.pdf.user', '用户'),
('zh', 'reports.pdf.statistics', '统计'),
('zh', 'reports.pdf.entries', '条目'),
('zh', 'reports.pdf.per_day', '每天'),
('zh', 'reports.pdf.achievements', '成就'),
('zh', 'reports.pdf.mood', '心情'),
('zh', 'reports.pdf.ai_analysis', 'AI 分析'),
('zh', 'reports.pdf.entries_period', '期间条目'),
('zh', 'reports.pdf.achievement_badge', '成就'),
('zh', 'reports.pdf.more_entries', '... 还有 {count} 个条目'),
('zh', 'reports.pdf.generated_by', '由 UNITY 生成'),
('zh', 'reports.pdf.weekly_report', '周报'),
('zh', 'reports.pdf.monthly_report', '月报'),

-- Japanese
('ja', 'reports.pdf.title', 'UNITY レポート'),
('ja', 'reports.pdf.user', 'ユーザー'),
('ja', 'reports.pdf.statistics', '統計'),
('ja', 'reports.pdf.entries', 'エントリ'),
('ja', 'reports.pdf.per_day', '1日あたり'),
('ja', 'reports.pdf.achievements', '達成'),
('ja', 'reports.pdf.mood', '気分'),
('ja', 'reports.pdf.ai_analysis', 'AI 分析'),
('ja', 'reports.pdf.entries_period', '期間中のエントリ'),
('ja', 'reports.pdf.achievement_badge', '達成'),
('ja', 'reports.pdf.more_entries', '... さらに {count} 件のエントリ'),
('ja', 'reports.pdf.generated_by', 'UNITY によって生成'),
('ja', 'reports.pdf.weekly_report', '週間レポート'),
('ja', 'reports.pdf.monthly_report', '月間レポート'),

-- Georgian
('ka', 'reports.pdf.title', 'UNITY ანგარიში'),
('ka', 'reports.pdf.user', 'მომხმარებელი'),
('ka', 'reports.pdf.statistics', 'სტატისტიკა'),
('ka', 'reports.pdf.entries', 'ჩანაწერები'),
('ka', 'reports.pdf.per_day', 'დღეში'),
('ka', 'reports.pdf.achievements', 'მიღწევები'),
('ka', 'reports.pdf.mood', 'განწყობა'),
('ka', 'reports.pdf.ai_analysis', 'AI ანალიზი'),
('ka', 'reports.pdf.entries_period', 'პერიოდის ჩანაწერები'),
('ka', 'reports.pdf.achievement_badge', 'მიღწევა'),
('ka', 'reports.pdf.more_entries', '... და კიდევ {count} ჩანაწერი'),
('ka', 'reports.pdf.generated_by', 'გენერირებული UNITY-ის მიერ'),
('ka', 'reports.pdf.weekly_report', 'კვირის ანგარიში'),
('ka', 'reports.pdf.monthly_report', 'თვის ანგარიში'),

-- Kazakh
('kk', 'reports.pdf.title', 'UNITY есебі'),
('kk', 'reports.pdf.user', 'Пайдаланушы'),
('kk', 'reports.pdf.statistics', 'Статистика'),
('kk', 'reports.pdf.entries', 'Жазбалар'),
('kk', 'reports.pdf.per_day', 'Күніне'),
('kk', 'reports.pdf.achievements', 'Жетістіктер'),
('kk', 'reports.pdf.mood', 'Көңіл-күй'),
('kk', 'reports.pdf.ai_analysis', 'AI талдау'),
('kk', 'reports.pdf.entries_period', 'Кезеңдегі жазбалар'),
('kk', 'reports.pdf.achievement_badge', 'Жетістік'),
('kk', 'reports.pdf.more_entries', '... және тағы {count} жазба'),
('kk', 'reports.pdf.generated_by', 'UNITY арқылы жасалған'),
('kk', 'reports.pdf.weekly_report', 'Апталық есеп'),
('kk', 'reports.pdf.monthly_report', 'Айлық есеп')

ON CONFLICT (lang_code, translation_key) DO UPDATE
SET translation_value = EXCLUDED.translation_value,
    updated_at = NOW();


